apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: humanitec
  namespace: ${NAMESPACE}
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - git:
      repoURL: ${REPO_URL}
      revision: HEAD
      directories:
      - path: "*/*"
  template:
    metadata:
      name: "hum-{{index .path.segments 0}}-{{index .path.segments 1}}"
    spec:
      project: default
      source:
        repoURL: ${REPO_URL}
        targetRevision: HEAD
        path: "{{index .path.segments 0}}/{{index .path.segments 1}}"
      destination:
        server: "https://kubernetes.default.svc"
        namespace: "hum-{{index .path.segments 0}}-{{index .path.segments 1}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
  syncPolicy:
    applicationsSync: sync
