kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
  namespace: rhdh
data:
  app-config-rhdh.yaml: |
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh.${basedomain}
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh.${basedomain}
      cors:
        origin: https://backstage-developer-hub-rhdh.${basedomain}
    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]
      providers:
        # github discovery plugin isn't installed yet.
        # github:
        #   githubOrg:
        #     organization: ${GITHUB_ORG_ID}
      locations:
        - type: url
          target: https://github.com/humanitec-architecture/backstage/blob/main/templates/podinfo-example/template.yaml
        - type: url
          target: https://github.com/humanitec-architecture/backstage/blob/main/templates/node-service/template.yaml
        - type: url
          target: https://github.com/humanitec-architecture/reference-architecture-rhos/blob/main/backstage-templates/quarkus-todo/template.yaml
    dynamicPlugins:
      # See https://github.com/janus-idp/backstage-showcase/blob/main/showcase-docs/dynamic-plugins.md#frontend-layout-configuration
      frontend:
        humanitec.backstage-plugin:
          mountPoints:
            - mountPoint: entity.page.overview/cards
              importName: HumanitecCardComponent
              config:
                layout:
                  gridColumn:
                    lg: '5 / -1'
                    md: '3 / -1'
                    xs: '1 / -1'
                if:
                  allOf:
                    - isKind: component
          scaffolderFieldExtensions:
            - importName: ValidateHumanitecAppIDFieldExtension

    humanitec:
      orgId: ${HUMANITEC_ORG_ID}
      token: ${HUMANITEC_TOKEN} # without Bearer
      cloudProvider: aws
      githubOrgId: ${GITHUB_ORG_ID}

    auth:
      # see https://backstage.io/docs/auth/ to learn about auth providers
      environment: development
      providers:
        github:
          development:
            clientId: ${GITHUB_APP_CLIENT_ID}
            clientSecret: ${GITHUB_APP_CLIENT_SECRET}
    integrations:
      github:
        - host: github.com
          apps:
            - appId: ${GITHUB_APP_APP_ID}
              clientId: ${GITHUB_APP_CLIENT_ID}
              clientSecret: ${GITHUB_APP_CLIENT_SECRET}
              webhookUrl: ${GITHUB_APP_WEBHOOK_URL}
              webhookSecret: ${GITHUB_APP_WEBHOOK_SECRET}
              privateKey: |
                ${GITHUB_APP_PRIVATE_KEY}
