apiVersion: humanitec.io/v1alpha1
kind: SecretStore
metadata:
  name: ${SECRET_STORE_ID}
  labels:
    app.humanitec.io/default-store: "true"
spec:
  awssm:
    region: ${SECRETS_MANAGER_REGION}
    auth:
      accessKeyIDSecretRef:
        name: ${SECRET_NAME}
        key: access_key_id
      secretAccessKeySecretRef:
        name: ${SECRET_NAME}
        key: secret_access_key
